// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgFPvNRo8P7qkgipbIZN_gV88Z9QgY_eE',
    appId: '1:779718382461:web:c5996d05f9fc6e9120b214',
    messagingSenderId: '779718382461',
    projectId: 'gymnastics-98d90',
    authDomain: 'gymnastics-98d90.firebaseapp.com',
    storageBucket: 'gymnastics-98d90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbnUdKJv26uClWBMaUYzfwFlrd856xh3c',
    appId: '1:779718382461:android:41f4d2fb2b37cc8a20b214',
    messagingSenderId: '779718382461',
    projectId: 'gymnastics-98d90',
    storageBucket: 'gymnastics-98d90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKxKJNmizg08ONOtyPgdAntOBbEXKEuss',
    appId: '1:779718382461:ios:69ce797048c938b320b214',
    messagingSenderId: '779718382461',
    projectId: 'gymnastics-98d90',
    storageBucket: 'gymnastics-98d90.firebasestorage.app',
    iosBundleId: 'com.gymnastics.gymnasticsClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKxKJNmizg08ONOtyPgdAntOBbEXKEuss',
    appId: '1:779718382461:ios:4a8d0c0705c5c5c120b214',
    messagingSenderId: '779718382461',
    projectId: 'gymnastics-98d90',
    storageBucket: 'gymnastics-98d90.firebasestorage.app',
    iosBundleId: 'com.example.gymnasticsClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgFPvNRo8P7qkgipbIZN_gV88Z9QgY_eE',
    appId: '1:779718382461:web:4b220ceec42287ca20b214',
    messagingSenderId: '779718382461',
    projectId: 'gymnastics-98d90',
    authDomain: 'gymnastics-98d90.firebaseapp.com',
    storageBucket: 'gymnastics-98d90.firebasestorage.app',
  );
}